### ISSUE TITLE
need SafeLoad and SafeDump analog to python

### ISSUE THREAD

**Issue by rurban** [ingydotnet/yaml-libyaml-pm#45]
In python you have to register safe classes which are then allowed to be dumped or loaded.
See the available metasploits to weaponize not being able to safe load.

This will need OO methods, not just the silly (no warnings 'once') options handling as of now.

```
$yaml = new YAML::XS::SafeLoader;
$yaml->add_safe("DateTime");
$yaml->SafeLoadFile("my.yml");
```

with a `!DateTime` object in the yml.

So the other methods should accept the optional 1st class arg also. And then you could just add the options behind the mandatory one-only string/filename/data argument as pairs as in python

**Comment by rurban** [comment]
I started implementing it now, with new Dumper, Loader, SafeDumper and SafeLoader classes,
and options as methods. A proper OO interface.

**Comment by rurban** [comment]
or maybe it's overkill to filter certain classes/tags and just disable them completely, as in `$YAML::Syck::LoadBlessed = 0;`

**Comment by perlpunk** [comment]
@rurban doesn't sound like overkill to me. do other implementations, like in python, support this?
of course i don't know what difference it would make regarding the amount of code.

**Comment by rurban** [comment]
@perlpunk yes, Python has it like described. I implemented it halfway in my `safe` branch. Have a look.

**Comment by nthykier** [comment]
Hi,

Anything that could speed up this ?  I was quite to surprised to learn that YAML::XS would load classes by default (especially when it has a "LoadCode" variable set to 0 that apparently controls something else).  Currently I am looking at an arbitrary code execution via YAML (CVE pending) and no option to solve it short of disabling my feature.

If possible, I would like to still have this feature, but I cannot support with YAML::XS not having a SafeLoad method.

**Comment by nthykier** [comment]
Bug link: https://bugs.debian.org/861958

**Comment by rurban** [comment]
See https://github.com/perl11/cperl/issues/198

**Comment by dod38fr** [comment]
Another possibility is to consider safe a class without DESTROY method. (I think this is the only way where "blessed" data can be harmful.)

Knowing that UNIVERSAL has no DESTROY method, It's fairly easy to test:

```
$ perl -MFile::Temp -E 'say File::Temp->can("DESTROY") ? "yes" : "no";'
yes
$ perl -E 'say UNIVERSAL->can("DESTROY") ? "yes" : "no";'
no
$ perl -MGetopt::Long -E 'say Getopt::Long->can("DESTROY") ? "yes" : "no";'
no
$ perl -MDateTime -E 'say DateTime->can("DESTROY") ? "yes" : "no";'
no
```

HTH

**Comment by rurban** [comment]
@dod38fr yes, agreed.

**Comment by jwilk** [comment]
I don't believe it's enough to check for the `DESTROY` method.

You normally process the unserialized data somehow, and that may invoke overloaded operators. E.g.:
```perl
package Very::Dangerous;

use overload '""' => sub {
	die "Eeek! ${\ref $_[0]} objects are not safe to stringify";
};

package main;

use YAML::XS;

my $d = Load('- !Very::Dangerous');
for (@{$d}) {
	print "$_\n";
}
```
dies with:
```
Eeek! Very::Dangerous objects are not safe to stringify at test.pl line 4.
```

Other theoretical problems with using the `can` method:

* An object can have a destructor even when `can` say it's missing, thanks to the `AUTOLOAD` mechanism. (But this was broken before Perl 5.24: <https://rt.perl.org/Public/Bug/Display.html?id=124387>).

* A class could override the `can` method. Mere checking for existence of `DESTROY` could cause execution of unwanted code.

**Comment by rurban** [comment]
Ok. 

* The first overload example can be checked for an overloaded class. (AMT magic). This should be enough.

But:
* The `can` override and `AUTOLOAD` mechanism to bring in undesired DETROY, so it cannot be safely checked. So we cannot declare such classes as safe. Better be safe and explicit without our safe declarations than sorry.

Thanks a lot!

**Comment by dod38fr** [comment]
I've prepared a [patch for Debian](https://anonscm.debian.org/cgit/pkg-perl/packages/libyaml-libyaml-perl.git/tree/debian/patches/add-safe-load) to provide a SafeLoad method (with self-tests). 

What do you think of this solution ?

If you want, I can prepare a PR for this repo.

All the best

**Comment by perlpunk** [comment]
@dod38fr Thanks.
I have been working/thinking on this, too.
My point of view on this is:
1) safe loading should become the default (at some point)
2) There shouldn't be a subroutine SafeLoad (and possible SafeLoadFile), but a more general Schema API that allows to enable/disable several schemas (like `!local` tags and `tag:example.org:foo`).

I am currently working on a pure perl parser YAML::PP and want to implement the API there first.
For most users that don't know about those YAML features this might sound like overkill, but that's what YAML was also designed for, and if we introduce SafeLoad now, we have to support this later too.

Personally, I would want to have safe loading rather today than tomorrow. I also talked to @ingydotnet, and he really doesn't want to introduce something like that before we have a standard API for it.

**Comment by perlpunk** [comment]
Btw, for being safe after a Load you can also try https://metacpan.org/pod/Data::Structure::Util
```perl
use Data::Structure::Util qw/ unbless circular_off /;
# unbless all objects
unbless( $data );
# and possibly remove circular refs
circular_off( $data );
```

**Comment by dod38fr** [comment]
@perlpunk hmm. ok. Good points.

I've disabled the patch: SafeLoad won't be shipped on Debian.

Thanks for the idea about using `unbless`. This gives another way to patch an insecure application. This is probably easier than replacing YAML::XS with YAML::Tiny.

All the best

**Comment by rurban** [comment]
Unblessing objects after being created is still insecure. They need to be
forbidden in the first place.

Am 11.11.2017 18:35 schrieb "Dominique Dumont" <notifications@github.com>:

**Comment by perlpunk** [comment]
@rurban, I agree that `unbless` is a workaround solution, and objects shouldn't be created at all, but I would be interested in how that could still be exploitable.

**Comment by perlpunk** [comment]
@dod38fr I started with a Schema implementation in YAML::PP, however, this is going to take more time, and even more time to support it in some way YAML::XS...
I'm leaning towards introducing a `$SafeLoad` variable now.
It would be false by default for now, and maybe set to true at some point.
Alternatively `$LoadObjects = 1`.
Of course, just like with `SafeLoad()`, this has to be supported in the future. It has the advantage that it covers also `LoadFile` without the need to write `SafeLoadFile()`
Unfortunately it has the usual disadvantages of such global variables, but that's the way YAML::XS works right now.

**Comment by rurban** [comment]
Well, that's why I converted the global infected XS API to a better functional interface in my safe branch

**Comment by perlpunk** [comment]
Maybe it helps if I write down what I would like to see in a new API, and why it should be called Schema.
The standard YAML Tags like `!!str`, `!!bool` are resolved with a schema in YAML 1.2.
(Since YAML::XS should support 1.2 in the future, it should support this).
YAML 1.2 has the schemas Failsafe, JSON and Core.
The tags like `!!perl/type:Class` can also be seen as a schema. (It should also be noted that YAML 1.2 suggests only one `!` for such a language specific schema, since `!!` is "reserved" for the standard schema.)
This schema could be called `Perl`.
And then there are local tags like `!Foo`. This can also be seen as a schema.
For each userdefined schema you should have fine grained control on the behaviour.
Additionally you can have a URI schema (the standard ones `!!` are actually shorthands for `!<tag:yaml.org,2002:...>`).

My wishes for the new API regarding loading Objects:
- Be able to turn on/off loading objects completely (that includes things like `!!perl/hash:Foo` and `!Foo`)
- Turn on/off loading generic objects via the Perl schema (`!!perl/hash:Foo`, `!perl/hash:Foo`)
- Turn on/off loading objects from local tags (`!Foo`)
- Enable only certain classes (specific ones and via regex)
- Decide what to do for certain classes via callback (i.e. you might want to do a `Class->new($yamldata)` or `Class->inflate($yamldata)` instead of just `bless $yamldata, "Class"`).
- Create an object from a matching regex (see the Dice examples in the PyYAML documentation: http://pyyaml.org/wiki/PyYAMLDocumentation)
- Also you need the same kind of control over Dumping

This is what YAML was made for, and in other languages people are actually using this.

That's why I think now that simple adding `SafeLoad` or `$SafeLoad` will not be enough for the future. But OTOH we should make it safe ASAP.

**Comment by dod38fr** [comment]
@perlpunk Having a `$SafeLoad` global variable is better than nothing. 

I'd rather see `$SafeLoad` than `$LoadObject` because:
* its name is more likely to catch the attention of users than `$LoadObjects`: everybody is concerned by safety. On the other hand most people don't care about loading objects in Yaml so `$loadObject` is more likely to be ignored.
* its default value is falsy, i.e. a missing value means falsy, which is easier to handle than a missing value meaning truthy value

Thanks for your work on YAML.

All the best

**Comment by perlpunk** [comment]
as I cannot decide this, trying to get feedback from @ingydotnet ...

**Comment by ingydotnet** [comment]
After talking to @perlpunk on the phone, the quickest solution is to add a `$YAML::XS::LoadBlessed` global that can be set to `0` or `1`, and will default to `1` for now.

This global var name was chosen because it is already present in YAML::Syck. I didn't want to add any more globals, but @perlpunk convinced me it was best in this case. We are working on a new API for all YAML modules (pm XS Syck); it won't have globals, and no need to get fancy on the legacy global solution.

Expect this fix to be out in short order...

**Comment by dod38fr** [comment]
Fair enough. I'm fine with `$YAML::XS::LoadBlessed ` global.

Thanks for your work.

All the best

**Comment by perlpunk** [comment]
PR #73 created

**Comment by perlpunk** [comment]
Sorry, I missed some spots as I was only looking for the call `sv_bless`. Will do another PR.

**Comment by perlpunk** [comment]
PR #74 created

**Comment by perlpunk** [comment]
Released YAML-LibYAML-0.69.tar.gz
thanks for all comments!

**Comment by perlpunk** [comment]
@rurban I would be interested in why you still say that YAML::XS is vulnerable in https://news.ycombinator.com/item?id=16469364
Also I asked you before how using unbless() would be exploitable if you use YAML::XS < 0.69, but I didn't get an answer.
I think it would be more productive to discuss that here instead of spreading potential FUD.
If `$LoadBlessed = 0` is vulnerable, I would like to hear about it.
If `unless` is vulnerable I'd like to hear about it.
I'm interested in making it safe, and if I wrote something wrong in my article, I would like to fix it.

Note: I know that Data::Structure::Util has problems with tied data, but YAML::XS does not produce such data. YAML.pm does when using `$YAML::Preserve`, maybe I should mention that in the article.

**Comment by jwilk** [comment]
The `unbless` approach is indeed insecure. The example code from the blog post looks like this:
```perl
use Data::Structure::Util qw/ unbless /;
my $data = Load $yaml;
unbless $data;
```
But `Load` can return a list, and then you unbless only the last element.
There's a much bigger problem, though: if YAML is not syntactically correct, `unbless` won't even get a chance to be run.

Proof of concept:
```perl
package Very::Dangerous;

sub DESTROY {
	print STDERR "Eeek!\n";
}

package main;

use YAML::XS;
use Data::Structure::Util qw/ unbless /;

my $yaml = "!Very::Dangerous\n---\n:";
my @data = Load $yaml;
unbless @data;
```
Here's what happens:
```
YAML::XS::Load Error: The problem:

    did not find expected key

was found at document: 2, line: 3, column: 1
while parsing a block mapping at line: 3, column: 1
Eeek!
```

**Comment by perlpunk** [comment]
@jwilk Thanks for the hint about the list!
Yes, it's correct that you should always assign to an array.

Also thanks for the second example. I did not think about that one. It's also not possible to catch that with an eval.
YAML::XS will start to bless things during parsing, so there's no way to prevent that.

I will edit my article!

**Comment by perlpunk** [comment]
Edited the article. Sorry for writing a misleading article.

Now still missing from @rurban is how to exploit YAML::XS 0.69

**Comment by rurban** [comment]
Read my docs and watch the video

http://search.cpan.org/~rurban/Cpanel-JSON-XS-4.02/XS.pm#SECURITY_CONSIDERATIONS
"Watch https://www.youtube.com/watch?v=Gzx6KlqiIZE for an exploit demo for "CVE-2015-1592 SixApart MovableType Storable Perl Code Execution" for a deserializer which expands objects. Deserializing even coderefs (methods, functions) or external data would be considered the most dangerous."

**Comment by perlpunk** [comment]
@rurban My question is rather, is it still exploitable if setting `$YAML::XS::LoadBlessed = 0`. I know it's bad that the default is currently 1, and we might change this in the future, but how can it be exploited? Only if I forgot something in my fix. The video is from 2015, so it can't have tested YAML::XS 0.69.

**Comment by rurban** [comment]
The video is for Storable, but an attacker would use the same mechanisms as shown there. @jwilk hinted at it also.
With `$YAML::XS::LoadBlessed = 0` of course this method would not work. But most people do want whitelisting, and know it from python.

**Comment by perlpunk** [comment]
@rurban then please don't keep saying that YAML::XS is vulnerable in this regard.
(I still would personally not load untrusted YAML with it because of potential memory leaks, stack overflows. If, then I would run it in its own process, limit the input size and the process ressources. But it won't create objects.)

PyYAML implements its constructor in python, while YAML::XS is (almost) completely written in C.
PyYAML lets you define custom constructors, and that's something I started to implement in YAML::PP, too.

We discussed already why we didn't want to add a simple whitelisting mechanism in YAML::XS for now.
Adding an API like I plan for YAML::PP will be a lot of work for YAML::XS.
Maybe a Perl frontend with libyaml backend would be useful.

If you want to load untrusted YAML *and* want objects, you have to wait a bit until YAML::PP can do it.

**Comment by rurban** [comment]
> If you want to load untrusted YAML and want objects, you have to wait a bit until YAML::PP can do it.

No. Just use my variant from cperl, which is fast and safe. And is usable for CPAN, unlike your variant.
